class CuteCat {
  String name;
  String picture;
  String description;
  int age;
  String gender;
  String uniqueValue;
  String personalityTraits;
  String location;

  CuteCat({
    required this.name,
    required this.picture,
    required this.description,
    required this.age,
    required this.gender,
    required this.uniqueValue,
    required this.personalityTraits,
    required this.location,
  });
}

var cuteCatList = [
  CuteCat(
    name: 'Mochi',
    picture: 'assets/images/cute_cat_01.jpg',
    description: 'Mochi is a spirited and adventurous cat with an insatiable curiosity about the world around him. His energy is boundless, and he loves exploring every corner of the house, always on the move and eager to discover new territories. Whether it\'s climbing to the highest perch, investigating a mysterious sound, or darting through unexpected hiding spots, Mochi approaches life with unbridled enthusiasm. His playful spirit and constant sense of wonder make him an irresistible companion who brings excitement and joy to his family\'s daily life.',
    age: 2,
    gender: 'Male',
    uniqueValue: 'Loves climbing trees',
    personalityTraits: 'Adventurous, Energetic, Curious',
    location: 'New York',
  ),
  CuteCat(
    name: 'Luna',
    picture: 'assets/images/cute_cat_02.jpg',
    description: 'Luna is an adorable and tender-hearted kitten who embodies pure gentleness and affection. Her soft purrs and delicate demeanor captivate everyone around her. She craves warmth and comfort, always seeking out cozy laps and gentle cuddles. Despite her shy nature, Luna has a deep capacity for love and connection. Her large, expressive eyes seem to communicate volumes of emotion, drawing people into her sweet world. When she feels safe, she transforms from a timid kitten into a loving companion, softly kneading and nestling close, radiating a sense of pure, unconditional love.',
    age: 1,
    gender: 'Female',
    uniqueValue: 'Loves meowing',
    personalityTraits: 'Affectionate, Gentle, Shy',
    location: 'Tokyo',
  ),
  CuteCat(
    name: 'Simba',
    picture: 'assets/images/cute_cat_03.jpg',
    description: 'Simba is a courageous and intellectually curious cat who approaches life as one grand adventure. His keen intelligence is matched only by his bold spirit, always ready to explore new environments with determination and excitement. Whether investigating a strange noise, learning a new trick, or strategically planning his next playful move, Simba demonstrates an remarkable blend of bravery and mental sharpness. His confident demeanor and quick thinking make him stand out, turning everyday moments into thrilling experiences. With an alert gaze and a posture that suggests constant readiness, Simba embodies the perfect balance of courage and curiosity.',
    age: 3,
    gender: 'Male',
    uniqueValue: 'Enjoys watching TV',
    personalityTraits: 'Brave, Intelligent, Confident',
    location: 'Chicago',
  ),
  CuteCat(
    name: 'Milo',
    picture: 'assets/images/cute_cat_04.jpg',
    description: 'Milo is a mischievous and razor-sharp feline with an uncanny ability to outsmart everyone around him. His clever pranks and ingenious strategies keep his family constantly entertained and slightly on edge. With a twinkle in his eye and an unmistakable air of cunning, Milo navigates his world like a master strategist. He has an extraordinary talent for getting exactly what he wants, whether it\'s an extra treat, a prime sleeping spot, or simply the undivided attention of his humans. His loyalty is as impressive as his intelligence, forming deep bonds while maintaining his cheeky and independent spirit.',
    age: 4,
    gender: 'Male',
    uniqueValue: 'Prefers human food',
    personalityTraits: 'Cheeky, Smart, Loyal',
    location: 'Jakarta',
  ),
  CuteCat(
    name: 'Cleo',
    picture: 'assets/images/cute_cat_05.jpg',
    description: 'Cleo is an exquisitely graceful cat who moves through life with remarkable poise and elegance. Her sophisticated charm is evident in every movement, from the way she delicately steps across rooms to her serene manner of basking in warm sunlight. Despite her initial shyness around men, she radiates a calm and friendly energy that draws people toward her. Her beautiful coat and regal posture make her seem almost like a living work of art. When comfortable, Cleo transforms into a gentle companion, sharing moments of quiet affection and radiating a sense of tranquil beauty that captivates everyone around her.',
    age: 5,
    gender: 'Female',
    uniqueValue: 'Shy with man',
    personalityTraits: 'Calm, Graceful, Friendly',
    location: 'Miami',
  ),
  CuteCat(
    name: 'Shadow',
    picture: 'assets/images/cute_cat_06.jpg',
    description: 'Shadow is a profoundly enigmatic cat with mesmerizing blue eyes that seem to hold deep, unspoken stories. His contemplative nature sets him apart, as he observes the world with an intense and mysterious demeanor. Unlike typical energetic felines, Shadow finds comfort in quiet observation, carefully studying his surroundings with a wisdom that seems beyond his years. His independence is striking, preferring moments of solitude where he can reflect and contemplate. Yet, for those who earn his trust, Shadow reveals glimpses of a loyal and sensitive soul, creating deep connections through his quiet, meaningful presence.',
    age: 3,
    gender: 'Male',
    uniqueValue: 'Has striking blue eyes',
    personalityTraits: 'Quiet, Observant, Independent',
    location: 'Seattle',
  ),
  CuteCat(
    name: 'Bella',
    picture: 'assets/images/cute_cat_07.jpg',
    description: 'Bella is a vivacious and effervescent kitten who bursts with limitless energy and an infectious enthusiasm for life. Her playful spirit knows no bounds, as she bounces around the house with remarkable agility and joy. Every moment is an opportunity for adventure, whether it\'s chasing laser dots, pouncing on toys, or exploring every nook and cranny. Her curious nature drives her to investigate everything with wide-eyed wonder and unbridled excitement. Bella\'s personality is a whirlwind of pure happiness, spreading laughter and joy wherever she goes, making her an irresistible bundle of feline energy.',
    age: 2,
    gender: 'Female',
    uniqueValue: 'Loves lasers',
    personalityTraits: 'Playful, Energetic, Curious',
    location: 'Boston',
  ),
  CuteCat(
    name: 'Leo',
    picture: 'assets/images/cute_cat_08.jpg',
    description: 'Leo is a gentle giant who embodies tranquility and contentment in its purest form. His massive frame belies a soft, peaceful nature that radiates calm throughout the household. He has perfected the art of relaxation, finding his favorite spot and transforming it into a sanctuary of comfort. Long, uninterrupted naps are his specialty, and he approaches life with a serene philosophy that seems to say, "Why rush?" Despite his laid-back demeanor, Leo is incredibly loyal, forming deep bonds with his family. His consistent, soothing presence provides a sense of security and unconditional love.',
    age: 6,
    gender: 'Male',
    uniqueValue: 'Same spot naps',
    personalityTraits: 'Relaxed, Loyal, Gentle',
    location: 'Dallas',
  ),
  CuteCat(
    name: 'Zoe',
    picture: 'assets/images/cute_cat_09.jpg',
    description: 'Zoe is a delightful and incredibly inquisitive kitten who approaches every moment as a new opportunity for discovery. Her world is a constant adventure, with eyes wide with wonder and tiny paws always ready to investigate. Nothing escapes her curiosity - from the tiniest movement to the most obscure corner of the room. Her energetic and friendly nature means she\'s always eager to engage, whether it\'s playing with her humans or exploring a new environment. Zoe\'s unique, quirky meow adds an extra layer of charm to her already endearing personality, making her an absolute joy to be around.',
    age: 1,
    gender: 'Female',
    uniqueValue: 'Has a quirky meow',
    personalityTraits: 'Curious, Energetic, Friendly',
    location: 'Austin',
  ),
  CuteCat(
    name: 'Max',
    picture: 'assets/images/cute_cat_10.jpg',
    description: 'Max is a hilariously mischievous cat with an oversized personality that fills the entire room. His comedic timing and unexpected antics ensure there\'s never a dull moment in his household. From stealing socks to creating elaborate play scenarios, Max has an incredible talent for generating laughter. His playful behavior is both charming and ingenious, always keeping his family thoroughly entertained. Despite his cheeky nature, Max has a heart of gold, using his humor as a way to connect and spread joy. His ability to turn ordinary moments into hilarious adventures makes him an irreplaceable member of the family.',
    age: 2,
    gender: 'Male',
    uniqueValue: 'Steals socks',
    personalityTraits: 'Cheeky, Funny, Playful',
    location: 'Houston',
  ),
  CuteCat(
    name: 'Nala',
    picture: 'assets/images/cute_cat_11.jpg',
    description: 'Nala is a cunning and adventurous feline who turns every moment into an exciting game of strategy and surprise. Her playful nature is matched by an incredible ability to orchestrate surprise attacks and discover the most unexpected hiding places. No box, shelf, or dark corner is safe from her exploratory spirit. She keeps everyone on their toes with her unpredictable movements and clever tactics. Her adventurous personality means she\'s always ready for the next exciting challenge, approaching life with a mix of stealth, curiosity, and boundless energy that makes her an endlessly fascinating companion.',
    age: 3,
    gender: 'Female',
    uniqueValue: 'Hides in boxes',
    personalityTraits: 'Sneaky, Playful, Adventurous',
    location: 'Chicago',
  ),
  CuteCat(
    name: 'Charlie',
    picture: 'assets/images/cute_cat_12.jpg',
    description: 'Charlie is an incredibly affectionate and warmhearted cat who thrives on human connection. His gentle spirit and deep capacity for love make him an extraordinary companion. He seeks out belly rubs with an endearing persistence, always ready to shower his family with unconditional affection. His friendly demeanor means he\'s equally comfortable cuddling quietly or playing energetically, adapting seamlessly to his humans\' moods. Charlie\'s ability to sense emotions and provide comfort is remarkable, making him more than just a pet - he\'s a true emotional support companion who brings warmth and joy to every interaction.',
    age: 5,
    gender: 'Male',
    uniqueValue: 'Loves belly rubs',
    personalityTraits: 'Friendly, Gentle, Cuddly',
    location: 'Tokyo',
  ),
  CuteCat(
    name: 'Coco',
    picture: 'assets/images/cute_cat_13.jpg',
    description: 'Coco is a vibrant and nature-loving kitten whose enthusiasm for the outdoors is nothing short of infectious. Her entire world becomes an adventure playground, with butterflies serving as her primary source of fascination and excitement. Every blade of grass, every fluttering wing becomes an opportunity for exploration and play. Her boundless energy and wide-eyed curiosity transform even the most ordinary garden into a magical realm of discovery. Coco approaches life with an incredible sense of wonder, her friendly and energetic personality ensuring that every outdoor expedition is filled with joy, excitement, and endless potential for fun.',
    age: 1,
    gender: 'Female',
    uniqueValue: 'Always chases butterflies',
    personalityTraits: 'Curious, Energetic, Friendly',
    location: 'New York',
  ),
  CuteCat(
    name: 'Rocky',
    picture: 'assets/images/cute_cat_14.jpg',
    description: 'Rocky is a fearlessly bold cat who turns vertical surfaces into his personal playground. His adventurous spirit manifests in an uncanny ability to climb to the highest, most seemingly impossible spots with incredible confidence. Nothing is too high or challenging for Rocky, who approaches each climbing challenge with determination and grace. His unbreakable spirit of resilience is matched by a sense of adventure that knows no boundaries. Whether scaling bookshelves, curtains, or kitchen cabinets, Rocky demonstrates an impressive combination of physical prowess and unwavering courage, turning every environment into an exciting vertical landscape.',
    age: 4,
    gender: 'Male',
    uniqueValue: 'Climbs the highest spots',
    personalityTraits: 'Bold, Adventurous, Confident',
    location: 'Miami',
  ),
  CuteCat(
    name: 'Ruby',
    picture: 'assets/images/cute_cat_15.jpg',
    description: 'Ruby is the quintessential social butterfly of the feline world, thriving on human interaction with an infectious enthusiasm that instantly brightens any room. Her outgoing nature means she greets every visitor with genuine excitement, making everyone feel instantly welcomed and loved. Ruby\'s ability to read and adapt to different social situations is remarkable, ensuring she can charm both cat lovers and those who might be hesitant. Her friendly demeanor is balanced by a deep sense of affection, creating meaningful connections with everyone she meets. Ruby doesn\'t just enter a room - she transforms it with her vibrant, welcoming energy.',
    age: 3,
    gender: 'Female',
    uniqueValue: 'Always greets visitors',
    personalityTraits: 'Friendly, Outgoing, Affectionate',
    location: 'Jakarta',
  ),
  CuteCat(
    name: 'Gizmo',
    picture: 'assets/images/cute_cat_16.jpg',
    description: 'Gizmo is a perpetually playful cat whose entire existence revolves around the joy of play. Toys are not just objects to him, but portals to exciting adventures and endless entertainment. He bounces from one plaything to another with incredible energy, transforming mundane objects into sources of pure excitement. His infectious joy is impossible to ignore, lighting up the entire room with his enthusiastic antics. Whether it\'s strings, balls, or interactive toys, Gizmo approaches playtime with a level of commitment and happiness that is truly remarkable. His cheerful spirit ensures that boredom is never an option in his world.',
    age: 2,
    gender: 'Male',
    uniqueValue: 'Obsessed with strings',
    personalityTraits: 'Playful, Energetic, Cheerful',
    location: 'Dallas',
  ),
  CuteCat(
    name: 'Daisy',
    picture: 'assets/images/cute_cat_17.jpg',
    description: 'Daisy is a delightfully quirky cat who defies every conventional feline stereotype. Her most endearing trait is her unique habit of sitting like a human, which never fails to bring endless amusement to her family. Beyond her amusing posture, Daisy embodies a gentle and humorous spirit that makes her utterly charming. She approaches life with a sense of playful unpredictability, always ready to surprise and delight those around her. Her quirky mannerisms are matched by a sweet temperament, making her not just a pet, but a true source of joy and laughter in her household.',
    age: 4,
    gender: 'Female',
    uniqueValue: 'Sits like a human',
    personalityTraits: 'Quirky, Gentle, Funny',
    location: 'Houston',
  ),
  CuteCat(
    name: 'Tiger',
    picture: 'assets/images/cute_cat_18.jpg',
    description: 'Tiger is a majestic feline who carries himself with an air of regal dignity that commands attention and respect. His striking tiger-like stripes are more than just a physical feature - they\'re a testament to his confident and independent spirit. Each movement is calculated and graceful, reflecting an inner strength that goes beyond mere appearance. Despite his imposing presence, Tiger has a nuanced personality that reveals moments of surprising tenderness. His independent nature means he chooses his interactions carefully, making his moments of affection all the more precious. When he decides to connect, he does so with a depth of loyalty and understanding that reveals the true complexity of his character.',
    age: 5,
    gender: 'Male',
    uniqueValue: 'Has tiger-like stripes',
    personalityTraits: 'Regal, Confident, Independent',
    location: 'Tokyo',
  ),
  CuteCat(
    name: 'Willow',
    picture: 'assets/images/cute_cat_19.jpg',
    description: 'Willow is the epitome of a devoted companion, forming an unbreakable bond with her humans that transcends typical pet-owner relationships. Her loyalty is so profound that she follows her family everywhere, creating an almost spiritual connection of trust and love. Every step, every movement is motivated by her desire to be close to her loved ones. Her friendly nature means she\'s not just a follower, but an active participant in family life, bringing comfort and joy with her constant presence. Willow\'s caring spirit is evident in the way she seems to sense emotions, offering silent support during challenging times and amplifying happiness during moments of celebration.',
    age: 3,
    gender: 'Female',
    uniqueValue: 'Follows you everywhere',
    personalityTraits: 'Loyal, Friendly, Caring',
    location: 'Austin',
  ),
  CuteCat(
    name: 'Oliver',
    picture: 'assets/images/cute_cat_20.jpg',
    description: 'Oliver is the embodiment of pure contentment, radiating happiness and tranquility in every moment of his existence. His perpetually relaxed demeanor transforms any space into a sanctuary of calm. The constant, soothing purrs that emanate from him are like a gentle melody of joy, filling the home with a sense of peace and comfort. Unlike more hyperactive cats, Oliver finds profound satisfaction in simple pleasures - a warm sunbeam, a soft cushion, or the quiet companionship of his humans. His loving nature means he\'s always ready to offer comfort, his serene presence acting as a natural stress reliever for everyone around him.',
    age: 2,
    gender: 'Male',
    uniqueValue: 'Always purring',
    personalityTraits: 'Relaxed, Happy, Loving',
    location: 'Miami',
  ),
];